package repository

import (
	"database/sql"
	"fmt"
	"happy-fridge-rest-api/happy-fridge-rest-api/cmd/internal/domain"
	"strings"

	"github.com/jmoiron/sqlx"
	"github.com/lib/pq"
)

type sqlFridgeRepository struct {
	db *sqlx.DB
}

func newSQLFridgeRepository(db *sqlx.DB) FridgeRepository {
	return &sqlFridgeRepository{db: db}
}

// Create inserts a new fridge. Populates ID and Code (Code is generated by DB trigger).
func (r *sqlFridgeRepository) Create(fridge *domain.Fridge) error {
	query := `INSERT INTO fridges (user_id, level, consumed_on_time, consumed_all,
                      consumed_meat_exp, consumed_milk_exp, consumed_vegetables_exp,
                      consumed_fruit_exp, consumed_sweets_exp, consumed_backery_exp,
                      consumed_seafood_exp, consumed_cooked_exp, consumed_other_exp,
                      is_one_day_notification, is_three_day_notification, is_five_day_notification,
                      ach_hello_world, ach_equator, ach_salad)
              VALUES (:user_id, :level, :consumed_on_time, :consumed_all,
                      :consumed_meat_exp, :consumed_milk_exp, :consumed_vegetables_exp,
                      :consumed_fruit_exp, :consumed_sweets_exp, :consumed_backery_exp,
                      :consumed_seafood_exp, :consumed_cooked_exp, :consumed_other_exp,
                      :is_one_day_notification, :is_three_day_notification, :is_five_day_notification,
                      :ach_hello_world, :ach_equator, :ach_salad)
              RETURNING id, code`

	stmt, err := r.db.PrepareNamed(query)
	if err != nil {
		return domain.ErrDatabase(fmt.Errorf("failed to prepare fridge create statement: %w", err))
	}
	defer stmt.Close()

	err = stmt.QueryRowx(fridge).Scan(&fridge.ID, &fridge.Code) // Scan string code
	if err != nil {
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" && pqErr.Constraint == "fridges_user_id_key" {
			return domain.NewAppError(err, fmt.Sprintf("User %d already has a fridge", fridge.UserID), 409)
		}
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23503" && pqErr.Constraint == "fk_user" {
			return domain.ErrNotFound("User", fridge.UserID)
		}
		return domain.ErrDatabase(fmt.Errorf("failed to execute fridge create statement: %w", err))
	}

	return nil
}

// FindByUserID retrieves a fridge associated with a user ID.
func (r *sqlFridgeRepository) FindByUserID(userID int64) (*domain.Fridge, error) {
	fridge := &domain.Fridge{}
	query := `SELECT * FROM fridges WHERE user_id = $1` // Select * gets all current columns
	err := r.db.Get(fridge, query, userID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, domain.ErrFridgeNotFoundForUser(userID)
		}
		return nil, domain.ErrDatabase(fmt.Errorf("failed to query fridge by user_id: %w", err))
	}
	return fridge, nil
}

// FindByID retrieves a fridge by its ID.
func (r *sqlFridgeRepository) FindByID(id int64) (*domain.Fridge, error) {
	fridge := &domain.Fridge{}
	query := `SELECT * FROM fridges WHERE id = $1`
	err := r.db.Get(fridge, query, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, domain.ErrNotFound("Fridge", id)
		}
		return nil, domain.ErrDatabase(fmt.Errorf("failed to query fridge by id: %w", err))
	}
	return fridge, nil
}

// Update modifies an existing fridge (used for level, counters, etc.).
func (r *sqlFridgeRepository) Update(fridge *domain.Fridge) error {
	if fridge.ID == 0 {
		return domain.ErrBadRequest("Fridge ID is required for update")
	}
	query := `UPDATE fridges SET
                user_id = :user_id, code = :code, level = :level,
                consumed_on_time = :consumed_on_time, consumed_all = :consumed_all,
                consumed_meat_exp = :consumed_meat_exp, consumed_milk_exp = :consumed_milk_exp,
                consumed_vegetables_exp = :consumed_vegetables_exp, consumed_fruit_exp = :consumed_fruit_exp,
                consumed_sweets_exp = :consumed_sweets_exp, consumed_backery_exp = :consumed_backery_exp,
                consumed_seafood_exp = :consumed_seafood_exp, consumed_cooked_exp = :consumed_cooked_exp,
                consumed_other_exp = :consumed_other_exp,
                is_one_day_notification = :is_one_day_notification,
                is_three_day_notification = :is_three_day_notification,
                is_five_day_notification = :is_five_day_notification,
                ach_hello_world = :ach_hello_world, ach_equator = :ach_equator, ach_salad = :ach_salad
              WHERE id = :id`

	res, err := r.db.NamedExec(query, fridge)
	if err != nil {
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" {
			if pqErr.Constraint == "fridges_user_id_key" {
				return domain.NewAppError(err, fmt.Sprintf("User %d already assigned to another fridge", fridge.UserID), 409)
			}
			if pqErr.Constraint == "fridges_code_key" {
				return domain.NewAppError(err, fmt.Sprintf("Fridge code '%s' already exists", fridge.Code), 409)
			}
		}
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23503" {
			if pqErr.Constraint == "fk_user" {
				return domain.ErrNotFound("User", fridge.UserID)
			}
		}
		return domain.ErrDatabase(fmt.Errorf("failed to execute fridge update statement: %w", err))
	}
	count, _ := res.RowsAffected()
	if count == 0 {
		return domain.ErrNotFound("Fridge", fridge.ID)
	}
	return nil
}

// IncrementCounter atomically increments a specific counter field.
func (r *sqlFridgeRepository) IncrementCounter(fridgeID int64, fieldName string, value int64) error {
	validFields := map[string]bool{
		"level": true, "consumed_on_time": true, "consumed_all": true,
		"consumed_meat_exp": true, "consumed_milk_exp": true, "consumed_vegetables_exp": true,
		"consumed_fruit_exp": true, "consumed_sweets_exp": true, "consumed_backery_exp": true,
		"consumed_seafood_exp": true, "consumed_cooked_exp": true, "consumed_other_exp": true,
	}
	if !validFields[fieldName] {
		return domain.ErrBadRequest(fmt.Sprintf("Invalid field name for increment: %s", fieldName))
	}

	query := fmt.Sprintf(`UPDATE fridges SET %s = %s + $1 WHERE id = $2`, fieldName, fieldName)
	res, err := r.db.Exec(query, value, fridgeID)
	if err != nil {
		return domain.ErrDatabase(fmt.Errorf("failed to increment fridge counter '%s': %w", fieldName, err))
	}
	count, _ := res.RowsAffected()
	if count == 0 {
		return domain.ErrNotFound("Fridge", fridgeID)
	}
	return nil
}

// UpdateNotificationSettings updates only the notification flags.
func (r *sqlFridgeRepository) UpdateNotificationSettings(fridgeID int64, settings *domain.UpdateNotificationSettingsRequest) error {
	fields := []string{}
	args := []interface{}{}
	argID := 1

	if settings.IsOneDay != nil {
		fields = append(fields, fmt.Sprintf("is_one_day_notification = $%d", argID))
		args = append(args, *settings.IsOneDay)
		argID++
	}
	if settings.IsThreeDay != nil {
		fields = append(fields, fmt.Sprintf("is_three_day_notification = $%d", argID))
		args = append(args, *settings.IsThreeDay)
		argID++
	}
	if settings.IsFiveDay != nil {
		fields = append(fields, fmt.Sprintf("is_five_day_notification = $%d", argID))
		args = append(args, *settings.IsFiveDay)
		argID++
	}

	if len(fields) == 0 {
		return domain.ErrBadRequest("No notification settings provided for update")
	}

	args = append(args, fridgeID)
	query := fmt.Sprintf(
		"UPDATE fridges SET %s WHERE id = $%d",
		strings.Join(fields, ", "),
		argID,
	)

	res, err := r.db.Exec(query, args...)
	if err != nil {
		return domain.ErrDatabase(fmt.Errorf("failed to update notification settings: %w", err))
	}

	count, _ := res.RowsAffected()
	if count == 0 {
		return domain.ErrNotFound("Fridge", fridgeID)
	}

	return nil
}

// UpdateAchievements updates specific achievement flags.
func (r *sqlFridgeRepository) UpdateAchievements(fridgeID int64, achHelloWorld, achEquator, achSalad *bool) error {
	fields := []string{}
	args := []interface{}{}
	argID := 1

	if achHelloWorld != nil {
		fields = append(fields, fmt.Sprintf("ach_hello_world = $%d", argID))
		args = append(args, *achHelloWorld)
		argID++
	}
	if achEquator != nil {
		fields = append(fields, fmt.Sprintf("ach_equator = $%d", argID))
		args = append(args, *achEquator)
		argID++
	}
	if achSalad != nil {
		fields = append(fields, fmt.Sprintf("ach_salad = $%d", argID))
		args = append(args, *achSalad)
		argID++
	}

	if len(fields) == 0 {
		return domain.ErrBadRequest("No achievement flags provided for update")
	}

	args = append(args, fridgeID)

	query := fmt.Sprintf(`UPDATE fridges SET %s WHERE id = $%d`, strings.Join(fields, ", "), argID)
	res, err := r.db.Exec(query, args...)
	if err != nil {
		return domain.ErrDatabase(fmt.Errorf("failed to update achievements: %w", err))
	}
	count, _ := res.RowsAffected()
	if count == 0 {
		return domain.ErrNotFound("Fridge", fridgeID)
	}
	return nil
}

// GetStats retrieves specific fields needed for calculating statistics.
func (r *sqlFridgeRepository) GetStats(fridgeID int64) (*domain.Fridge, error) {
	fridge := &domain.Fridge{}
	query := `SELECT id, consumed_on_time, consumed_all,
                consumed_meat_exp, consumed_milk_exp, consumed_vegetables_exp,
                consumed_fruit_exp, consumed_sweets_exp, consumed_backery_exp,
                consumed_seafood_exp, consumed_cooked_exp, consumed_other_exp
              FROM fridges WHERE id = $1`
	err := r.db.Get(fridge, query, fridgeID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, domain.ErrNotFound("Fridge", fridgeID)
		}
		return nil, domain.ErrDatabase(fmt.Errorf("failed to query fridge stats: %w", err))
	}
	return fridge, nil
}
